library ieee;
    use ieee.std_logic_1164.all;
    use ieee.numeric_std.all;

entity trs80mon is
    port (
        clock:    in std_logic;
        address:  in std_logic_vector(10 downto 0); 
        cs_n:     in std_logic;
        data_out: out std_logic_vector(7 downto 0)
    );
end entity;

architecture rtl of trs80mon is
    -- ROM from $3000 to $35FF (1536 bytes)
    type rom_type is array(0 to 1535) of std_logic_vector(7 downto 0);
    signal rom : rom_type := (
        X"AA", X"4D", X"4F", X"ED", X"73", X"F8", X"FF", X"31", 
        X"50", X"FF", X"2A", X"49", X"40", X"7C", X"FE", X"FF", 
        X"38", X"06", X"21", X"FF", X"FE", X"22", X"49", X"40", 
        X"CD", X"62", X"30", X"3E", X"3E", X"CD", X"6C", X"30", 
        X"3E", X"20", X"CD", X"6C", X"30", X"CD", X"92", X"30", 
        X"3A", X"10", X"FF", X"FE", X"3A", X"CA", X"AA", X"32", 
        X"E6", X"DF", X"FE", X"4C", X"CA", X"38", X"31", X"FE", 
        X"53", X"CA", X"7C", X"31", X"FE", X"47", X"CA", X"F5", 
        X"31", X"FE", X"4D", X"CA", X"1A", X"32", X"FE", X"49", 
        X"CA", X"C4", X"32", X"FE", X"4F", X"CA", X"D9", X"32", 
        X"FE", X"52", X"CA", X"F1", X"32", X"FE", X"51", X"CA", 
        X"5D", X"30", X"C3", X"1B", X"30", X"ED", X"7B", X"F8", 
        X"FF", X"C9", X"3E", X"0D", X"CD", X"6C", X"30", X"3E", 
        X"0A", X"C3", X"6C", X"30", X"F5", X"DB", X"EA", X"E6", 
        X"40", X"28", X"FA", X"F1", X"D3", X"EB", X"C9", X"7E", 
        X"B7", X"C8", X"CD", X"6C", X"30", X"23", X"18", X"F7", 
        X"DB", X"EA", X"E6", X"80", X"28", X"FA", X"DB", X"EB", 
        X"C9", X"DB", X"EA", X"E6", X"80", X"C8", X"DB", X"EB", 
        X"18", X"F7", X"21", X"10", X"FF", X"06", X"37", X"CD", 
        X"80", X"30", X"FE", X"0D", X"28", X"2E", X"FE", X"08", 
        X"28", X"12", X"FE", X"7F", X"28", X"0E", X"57", X"78", 
        X"B7", X"28", X"EC", X"7A", X"CD", X"6C", X"30", X"77", 
        X"23", X"05", X"18", X"E3", X"78", X"FE", X"37", X"28", 
        X"DE", X"2B", X"04", X"3E", X"08", X"CD", X"6C", X"30", 
        X"3E", X"20", X"CD", X"6C", X"30", X"3E", X"08", X"CD", 
        X"6C", X"30", X"18", X"CB", X"36", X"00", X"CD", X"62", 
        X"30", X"C9", X"1A", X"FE", X"20", X"C0", X"13", X"18", 
        X"F9", X"F5", X"0F", X"0F", X"0F", X"0F", X"CD", X"E2", 
        X"30", X"F1", X"E6", X"0F", X"C6", X"30", X"FE", X"3A", 
        X"38", X"02", X"C6", X"07", X"C3", X"6C", X"30", X"7C", 
        X"CD", X"D9", X"30", X"7D", X"C3", X"D9", X"30", X"CD", 
        X"09", X"31", X"07", X"07", X"07", X"07", X"47", X"CD", 
        X"09", X"31", X"B0", X"47", X"79", X"80", X"4F", X"78", 
        X"C9", X"CD", X"80", X"30", X"D6", X"30", X"FE", X"0A", 
        X"D8", X"E6", X"DF", X"D6", X"07", X"C9", X"CD", X"1F", 
        X"31", X"67", X"CD", X"1F", X"31", X"6F", X"C9", X"CD", 
        X"2C", X"31", X"07", X"07", X"07", X"07", X"47", X"CD", 
        X"2C", X"31", X"B0", X"C9", X"1A", X"13", X"D6", X"30", 
        X"FE", X"0A", X"D8", X"E6", X"DF", X"D6", X"07", X"C9", 
        X"CD", X"62", X"30", X"CD", X"80", X"30", X"FE", X"3A", 
        X"20", X"F9", X"0E", X"00", X"CD", X"F7", X"30", X"57", 
        X"CD", X"F7", X"30", X"67", X"CD", X"F7", X"30", X"6F", 
        X"CD", X"F7", X"30", X"FE", X"01", X"28", X"16", X"7A", 
        X"B7", X"28", X"08", X"CD", X"F7", X"30", X"77", X"23", 
        X"15", X"20", X"F8", X"CD", X"F7", X"30", X"3E", X"2E", 
        X"CD", X"6C", X"30", X"18", X"CE", X"CD", X"F7", X"30", 
        X"CD", X"89", X"30", X"21", X"35", X"33", X"CD", X"77", 
        X"30", X"C3", X"1B", X"30", X"11", X"11", X"FF", X"CD", 
        X"D2", X"30", X"CD", X"16", X"31", X"E5", X"CD", X"D2", 
        X"30", X"CD", X"16", X"31", X"D1", X"EB", X"CD", X"62", 
        X"30", X"7B", X"95", X"4F", X"7A", X"9C", X"38", X"45", 
        X"B7", X"20", X"09", X"79", X"FE", X"0F", X"30", X"04", 
        X"41", X"04", X"18", X"02", X"06", X"10", X"D5", X"3E", 
        X"3A", X"CD", X"6C", X"30", X"0E", X"00", X"78", X"CD", 
        X"D9", X"30", X"79", X"80", X"4F", X"7C", X"CD", X"D9", 
        X"30", X"79", X"84", X"4F", X"7D", X"CD", X"D9", X"30", 
        X"79", X"85", X"4F", X"AF", X"CD", X"D9", X"30", X"7E", 
        X"CD", X"D9", X"30", X"79", X"86", X"4F", X"23", X"10", 
        X"F6", X"79", X"ED", X"44", X"CD", X"D9", X"30", X"CD", 
        X"62", X"30", X"D1", X"18", X"B4", X"21", X"E9", X"31", 
        X"CD", X"77", X"30", X"CD", X"62", X"30", X"C3", X"1B", 
        X"30", X"3A", X"30", X"30", X"30", X"30", X"30", X"30", 
        X"30", X"31", X"46", X"46", X"00", X"11", X"11", X"FF", 
        X"CD", X"D2", X"30", X"CD", X"16", X"31", X"11", X"03", 
        X"32", X"D5", X"E9", X"F5", X"C5", X"D5", X"E5", X"E1", 
        X"22", X"06", X"FF", X"E1", X"22", X"04", X"FF", X"E1", 
        X"22", X"02", X"FF", X"E1", X"22", X"00", X"FF", X"C3", 
        X"1B", X"30", X"11", X"11", X"FF", X"CD", X"D2", X"30", 
        X"CD", X"16", X"31", X"E5", X"CD", X"D2", X"30", X"CD", 
        X"16", X"31", X"D1", X"7D", X"93", X"4F", X"7C", X"9A", 
        X"47", X"03", X"ED", X"43", X"08", X"FF", X"EB", X"CD", 
        X"62", X"30", X"ED", X"4B", X"08", X"FF", X"78", X"B1", 
        X"CA", X"1B", X"30", X"78", X"B7", X"20", X"08", X"79", 
        X"FE", X"10", X"30", X"03", X"57", X"18", X"02", X"16", 
        X"10", X"79", X"92", X"4F", X"78", X"DE", X"00", X"47", 
        X"ED", X"43", X"08", X"FF", X"E5", X"CD", X"EF", X"30", 
        X"3E", X"3A", X"CD", X"6C", X"30", X"3E", X"20", X"CD", 
        X"6C", X"30", X"5A", X"06", X"10", X"7B", X"B7", X"28", 
        X"0F", X"7E", X"CD", X"D9", X"30", X"3E", X"20", X"CD", 
        X"6C", X"30", X"23", X"1D", X"10", X"EF", X"18", X"0D", 
        X"3E", X"20", X"CD", X"6C", X"30", X"CD", X"6C", X"30", 
        X"CD", X"6C", X"30", X"10", X"F3", X"3E", X"20", X"CD", 
        X"6C", X"30", X"E1", X"42", X"7E", X"FE", X"20", X"38", 
        X"04", X"FE", X"7F", X"38", X"02", X"3E", X"2E", X"CD", 
        X"6C", X"30", X"23", X"10", X"EF", X"CD", X"62", X"30", 
        X"18", X"90", X"11", X"11", X"FF", X"CD", X"D2", X"30", 
        X"CD", X"16", X"31", X"CD", X"D2", X"30", X"1A", X"B7", 
        X"28", X"07", X"CD", X"1F", X"31", X"77", X"23", X"18", 
        X"F2", X"C3", X"1B", X"30", X"11", X"11", X"FF", X"CD", 
        X"D2", X"30", X"CD", X"1F", X"31", X"4F", X"ED", X"78", 
        X"CD", X"D9", X"30", X"CD", X"62", X"30", X"C3", X"1B", 
        X"30", X"11", X"11", X"FF", X"CD", X"D2", X"30", X"CD", 
        X"1F", X"31", X"4F", X"CD", X"D2", X"30", X"CD", X"1F", 
        X"31", X"ED", X"79", X"CD", X"62", X"30", X"C3", X"1B", 
        X"30", X"21", X"3A", X"33", X"CD", X"77", X"30", X"2A", 
        X"00", X"FF", X"7C", X"CD", X"D9", X"30", X"21", X"3D", 
        X"33", X"CD", X"77", X"30", X"2A", X"00", X"FF", X"7D", 
        X"CD", X"D9", X"30", X"21", X"41", X"33", X"CD", X"77", 
        X"30", X"2A", X"02", X"FF", X"CD", X"EF", X"30", X"21", 
        X"46", X"33", X"CD", X"77", X"30", X"2A", X"04", X"FF", 
        X"CD", X"EF", X"30", X"21", X"4B", X"33", X"CD", X"77", 
        X"30", X"2A", X"06", X"FF", X"CD", X"EF", X"30", X"CD", 
        X"62", X"30", X"C3", X"1B", X"30", X"4F", X"4B", X"0D", 
        X"0A", X"00", X"41", X"3D", X"00", X"20", X"46", X"3D", 
        X"00", X"20", X"42", X"43", X"3D", X"00", X"20", X"44", 
        X"45", X"3D", X"00", X"20", X"48", X"4C", X"3D", X"00", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", 
        X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF", X"FF"
    );



begin
    process(clock)
    begin
        if rising_edge(clock) then
            if cs_n = '0' then
                data_out <= rom(to_integer(unsigned(address)));
            end if;
        end if;
    end process;

end rtl;